### ISSUE TITLE
What else?

### ISSUE THREAD

**Issue by armendariz** [armendariz/terminal_recipes#2]
@taggartk what else should we go over? i did a quick sqlite thing you should look at and add to. is this all we need? other stuff need to go into the existing exercises?

**Comment by taggartk** [comment]
Thanks! This is the first thing I'm going to do when I get in tomorrow.

K

On Wed, Feb 4, 2015 at 10:58 AM, Agustin Armendariz <
notifications@github.com> wrote:

> @taggartk https://github.com/taggartk what else should we go over? i
> did a quick sqlite thing you should look at and add to. is this all we
> need? other stuff need to go into the existing exercises?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/armendariz/terminal_recipes/issues/2.

## 

Kendall Taggart | cell: 617.851.1379 | kendall.t.taggart@gmail.com
