### ISSUE TITLE
Use cut instead of awk in baby names examples?

### ISSUE THREAD

**Issue by taggartk** [armendariz/terminal_recipes#3]
Do we want to reference the cut command in the baby names example? We could use it instead of awk (passing a cut to grep). I realize we get to it in the contribs example. I'm going to make the change for now because I think repeating commands across examples instead of introducing new ones will be more clear. But let me know if you think otherwise.

**Comment by armendariz** [comment]
Yup. You're right. That's makes a lot more sense
