### ISSUE TITLE
csvsql issue

### ISSUE THREAD

**Issue by taggartk** [armendariz/terminal_recipes#5]
This command 
cat data/contribs.csv | sed 's/[\$,\,,)]//g' | in2csv -f csv | csvsql --tabs -i sqlite --table contribs --db sqlite:///contribs.sqlite --insert

is returning this error
csvsql: error: The --dialect option is only valid when --db is not specified.

Running to the airport now, but will take a look later. Let me know if you see the problem.

**Comment by armendariz** [comment]
Just take out the -i sqlite

Have a nice flight. Will check it out tomorrow morning

**Comment by taggartk** [comment]
I think I fixed the -i sqlite problem. But the table isn't importing correctly.

This works fine:

sqlite> SELECT COUNT(*) FROM contribs

But this 
sqlite> SELECT SUM(AMOUNT) FROM contribs;

Returns
Error: no such column: AMOUNT

Gonna head to the next panel, but can take a look later.

**Comment by armendariz** [comment]
Took the --tabs flag out and the -i sqlite. Should all work now.
